### ISSUE TITLE
ENHANCEMENT: Auto configure OBS to display grab-song output

### ISSUE THREAD

**Issue by strycore** [aFoxNamedMorris/grab-song#15]
Scenes in OBS are provided in JSON so it would be quite easy for grab-song to configure itself on the OBS side and could offer various presets. This would be even better when a GUI is implemented.

For the config files see: ~/.config/obs-studio/basic/scenes/*json

**Comment by aFoxNamedMorris** [comment]
Hmmm. I could do this. Will probably tie it in with a way to use different NoArt.jpg presets. Thanks!
One thing worth mentioning isnthat this should probably be optional, so as to not disrupt a person's custom scene.
