### ISSUE TITLE
Possible bug with RM_OUTPUT

### ISSUE THREAD

**Issue by 8BitCerberus** [aFoxNamedMorris/grab-song#21]
Whenever I add RM_OUTPUT to the command string, I get this error:

`RM_OUTPUT: command not found`

Everything else works as long as I don't add RM_OUTPUT to the command. I've tried adding it with  additional variables (such as ONELINE, OUTPUT_DIR, etc.) and I've also tried with just "RM_OUTPUT ./grab-song.sh"

Otherwise the script runs great, way better than my own hacked together monstrosity :)

**Comment by aFoxNamedMorris** [comment]
You have to set `RM_OUTPUT` to a value. I may have to update the documentation.

Upon investigating, I have reminded myself that RM_OUTPUT is a boolean. Set `RM_OUTPUT=true`. Setting `RM_OUTPUT=false` disables it.

**Comment by 8BitCerberus** [comment]
I wondered if that might be the case just never tried it since it wasn't in the documentation. Good to know, and thanks for the quick response!

**Comment by aFoxNamedMorris** [comment]
No problem! Glad to help.
