### ISSUE TITLE
Flatpak Workaround (Ubuntu 20.04 / Linux Mint 20)

### ISSUE THREAD

**Issue by Monstanner** [aFoxNamedMorris/grab-song#22]
This is a workaround for newer systems like Ubuntu 20.04 or systems based on it (e.g. Linux Mint 20) and for users of the Flatpak versions of the music player (Clementine 1.4).

0.0 Install dbus & dbus-x11 (if not pre-installed.)
1.0 Install qdbus-qt5 (This is required to request information from the music player and to send it again.)
2.0 Edit the grab-song.sh (You have to do that because the script can't find the files anymore.)
2.1 Change all $OUTPUT_DIR from the 121 to 124 line with the absolute path.
(e.g. SONG_TITLE="$OUTPUT_DIR/SongTitle.txt" becomes SONG_TITLE="/home/user1/Documents/grab-song-master/Output/SongTitle.txt)
2.2 Save and you're done

This workaround was tested on Linux Mint 20 XFCE and the Faltpak version by Clementine. I don't know if this works with other music players.

**Comment by aFoxNamedMorris** [comment]
I'll look into this. Unfortunately, I no longer have a Debian-based setup to test on, as I migrated to Manjaro. In the meantime, I recommend continuing to use your workaround until I can figure out how to avoid people editing the script or breaking portability.

**Comment by aFoxNamedMorris** [comment]
@Monstanner I tested Clementine 1.4 through Flatpak and I am not having any issues whatsoever. Did you `cd` to where the script is located before running? That is a requirement for proper operation.

**Comment by Monstanner** [comment]
`cd` didn't work for me either. But after I downloaded it again it works. It could also be that it was due to qdbus-qt5. It was not preinstalled on Linux Mint 20 and the script did not work there. But after I changed the path it worked. But now it works without it.

You can then close this issue. Thanks anyway.

**Comment by aFoxNamedMorris** [comment]
No problem! Thanks for stopping by.
