### ISSUE TITLE
[BUG] Images not being fetched from URL

### ISSUE THREAD

**Issue by GoldenFurredFox** [aFoxNamedMorris/grab-song#23]
No matter if there's a valid image at the URL for mpris:artUrl: it doesn't actually load the image.

This might be an issue with ImageMagick as well.

For testing purposes, try this on Ubuntu 20.04.1 LTS to see if you get the same problem.

**Comment by aFoxNamedMorris** [comment]
Hi! So sorry for the extremely late reply! There is a secondary dependency which some distros don't ship out of the box. I can't remember what it is right now, but if I get some time, I will be attempting to fix a few issues.

**Comment by aFoxNamedMorris** [comment]
This is an issue with Clementine through Flatpak. Closing.

**Comment by aFoxNamedMorris** [comment]
To those to whom it may concern:

You can fix this issue manually if you install an app called [Flatseal](https://github.com/tchx84/Flatseal).

Once launched, find Clementine and navigate to Filesystem.
Add a new location. Set it to `/tmp`.

**Comment by aFoxNamedMorris** [comment]
To whom it may concern:

You can fix this issue manually if you install an app called [Flatseal](https://github.com/tchx84/Flatseal).

Once launched, find Clementine and navigate to Filesystem.
Add a new location. Set it to `/tmp`.
