### ISSUE TITLE
Song Metadata incorrect for Devanagari Script

### ISSUE THREAD

**Issue by iAstrid** [aFoxNamedMorris/grab-song#24]
When running the script, the metadata picked from vlc of a playlist with complete title in Hindi is wrong. Please help me to fix this, I want to run this live anyhow!! I'm late on my timeline!
![IMG_20220115_094710](https://user-images.githubusercontent.com/97775488/149608943-64a7b3a1-c43c-4a26-8fe2-919f6573099e.jpg)

**Comment by aFoxNamedMorris** [comment]
This is beyond my understanding at the moment. This may take a while. I don't have a lot of time these days to work on Grab Song, but I will try and make a day of it soon, if possible.

**Comment by aFoxNamedMorris** [comment]
Alright! I was unable to reproduce the issue on my setup, but may have discovered the issue. I have pushed  commit 52a3b3a to try and resolve the issue. Please let me know if this works.
