### ISSUE TITLE
ENHANCEMENT: Update system.

### ISSUE THREAD

**Issue by aFoxNamedMorris** [aFoxNamedMorris/grab-song#5]
I am currently working on a system that will allow the script to update itself when a new version becomes available.

**Comment by aFoxNamedMorris** [comment]
I have been working on this carefully. When finished and implemented, grab-song.sh will check for an update, prompt the user to choose whether or not to update, and act accordingly. The configuration file will be kept between updates, and will simply  have new values added at next run. This will help ensure that a user's settings are preserved between updates.

**Comment by ghost** [comment]
Does this bring in any additional dependencies?

**Comment by aFoxNamedMorris** [comment]
No. Just 'cat', the 'mv' command, a couple of if/then statements, and 'wget', with an' unzip' command. Checks the local VERSION.md against master version.

**Comment by strycore** [comment]
If your preferred way of distributing your script is through git then you could do the same as oh-my-zsh which checks on updates weekly and simply does a git pull in the project's folder

**Comment by aFoxNamedMorris** [comment]
@strycore While yes, that would be a good way to go about it, I'm trying to keep the dependencies to a minimum. Also, with some of the changes we made, this was supposed to be closed. I had originally wanted this because I wanted people to be able to update the script without their config being overwritten. Now, with the validation system as scripted by @cptmashek, this idea is obsolete.
