### ISSUE TITLE
VLC 3.0.0: some album art fails to parse.

### ISSUE THREAD

**Issue by aFoxNamedMorris** [aFoxNamedMorris/grab-song#7]
Certain album art in VLC doesn't parse due to HTTP character tags in the image address. Spaces are already fixed.

**Comment by ghost** [comment]
Can you post an example so I can see about working on this? :)

Do we need to do some sanitizing, like escaping HTML sequences?

**Comment by aFoxNamedMorris** [comment]
It's the fact that VLC changes the spaces, special characters, and such with their %## equivalents.
"Dead Men Walking.jpg" becomes "Dead%20Men%20Walking.jpg", for example.

**Comment by ghost** [comment]
`./grab-song.sh vlc` output (modified to look okay in this comment) :

VLC version `2.2.1 Terry Pratchett (Weatherwax)`

```
===========================================================
Title: 二色蓮花蝶 ~ Ancients

Artist: あきやまうに

Album: 核熱造神ヒソウテンソク 東方非想天則 ORIGINAL SOUND TRACK
===========================================================
```

```
===========================
Title: Yo, Science

Artist: Kabuto the Python

Album: The Almighty
===========================
```

```
==============================
Title: Clockwise Operetta

Artist: Tomáš Dvořák

Album: Machinarium Soundtrack
==============================
```

It seems to have a split second of formatting error, but then fixes itself before I can really see what it's doing. That only happened when songs started that have diacritic letters.

**Comment by aFoxNamedMorris** [comment]
Huh. Curious. Good work, by the way.
